### ISSUE TITLE
attachment de errors.

### ISSUE THREAD

**Issue by Irigoshito** [S4kur4/AutoDeployCuckoo#13]
Hi, friend.

I enclose the errors that were presented in the new script, this is the entire execution plot.

Fabian O
[Log de errores provocados por el nuevo script.txt](https://github.com/S4kur4/AutoDeployCuckoo/files/7199398/Log.de.errores.provocados.por.el.nuevo.script.txt)
.

**Comment by S4kur4** [comment]
Hi Fabian,

Thanks for your testing, actually I also tested the script on an
Ubuntu18.04.5 after I sent you the message, and I met the same errors. The
root cause is I didn't upgrade "pip" before we use it to install Python
dependencies, so I added the command "pip install --upgrade pip", all the
Python dependencies would work normally.

https://github.com/S4kur4/AutoDeployCuckoo/blob/master/install.sh

I have release the new script, and it runs well on my test Ubuntu. You can
run the script directly through one line of command:

*bash <(curl -sS -L
https://raw.githubusercontent.com/S4kur4/AutoDeployCuckoo/master/install.sh
<https://raw.githubusercontent.com/S4kur4/AutoDeployCuckoo/master/install.sh>)*

And pls help me test again on your environment if you have any free time.
Thanks a lot, my friend.

s4kur4, from China.


Irigoshito ***@***.***> 于2021年9月21日周二 上午8:52写道：

**Comment by Irigoshito** [comment]
Hello S4kur
I have tested the changes you have made and it is working correctly.

I wanted to ask you for help with an error that I have at the time of executing the analysis and it tells me that it cannot connect between the host cuckoo computer and victim win7, I have made a ping between the two computers and they both respond.

I'm using another cuckoo virtual machine.


The following link is from a cuckoo virtual machine that I have been reviewing:

https://github.com/ashemery/CuckooVM

Atte.
FO

From: s4kur4 ***@***.***>
Date: Tuesday, 21 September 2021 at 20:27
To: S4kur4/AutoDeployCuckoo ***@***.***>
Cc: Irigoshito ***@***.***>, Author ***@***.***>
Subject: Re: [S4kur4/AutoDeployCuckoo] attachment de errors. (#13)
Hi Fabian,

Thanks for your testing, actually I also tested the script on an
Ubuntu18.04.5 after I sent you the message, and I met the same errors. The
root cause is I didn't upgrade "pip" before we use it to install Python
dependencies, so I added the command "pip install --upgrade pip", all the
Python dependencies would work normally.

https://github.com/S4kur4/AutoDeployCuckoo/blob/master/install.sh

I have release the new script, and it runs well on my test Ubuntu. You can
run the script directly through one line of command:

*bash <(curl -sS -L
https://raw.githubusercontent.com/S4kur4/AutoDeployCuckoo/master/install.sh
<https://raw.githubusercontent.com/S4kur4/AutoDeployCuckoo/master/install.sh>)*

And pls help me test again on your environment if you have any free time.
Thanks a lot, my friend.

s4kur4, from China.


Irigoshito ***@***.***> 于2021年9月21日周二 上午8:52写道：
