### ISSUE TITLE
Wget command

### ISSUE THREAD

**Issue by pietrogu** [S4kur4/AutoDeployCuckoo#4]
Hi,

I would like Agent.ova on an Ubuntu Server. Could you pleas previde a way to download the file using wget?

Thanks
Pietro

**Comment by S4kur4** [comment]
> Hi,
> 
> I would like Agent.ova on an Ubuntu Server. Could you pleas previde a way to download the file using wget?
> 
> Thanks
> Pietro

Sorry, I have tried searching for a way to freely stored the Agent.ova file, but due to the file is a little big (5.9GB), I didn't find a better way to save and share it. So chose my Onedrive disk space. Or do you have any better way to introduce? Maybe you can try some onedrive clients on Linux/Ubuntu?

**Comment by S4kur4** [comment]
Hey, I have changed the stored place for Agent.ova to Google Drive, see [issue 6](https://github.com/S4kur4/AutoDeployCuckoo/issues/6). And If you still want to use wget/curl, maybe you can get some help from this: https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive?page=1&tab=votes#tab-top
