### ISSUE TITLE
issue on install ubuntu 20?

### ISSUE THREAD

**Issue by killmasta93** [S4kur4/AutoDeployCuckoo#8]
Hi currently ran the script but im getting python-pip has not installation candidate
currently running ubuntu 20

**Comment by S4kur4** [comment]
> Hi currently ran the script but im getting python-pip has not installation candidate
> currently running ubuntu 20

This script did not test on Ubuntu 20, suggest you install python-pip manually at first. In addition, due to it has been a long period of time since I published this shell script, I consider that many Python dependencies have been upgraded more times, maybe you need to install Cuckoo step by step referring to this post [Install a Cuckoo Sandbox in 12 steps](https://0x0c.cc/2020/03/19/Install-a-Cuckoo-Sandbox-in-12-steps/), manually debug and troubleshooting will be needed as well.

**Comment by killmasta93** [comment]
thank for the reply, what ubuntu version did you install? with the script 
i read the steps which is 18.04.3 but could it be on a 18.04?

**Comment by killmasta93** [comment]
so tried installing manually using ubuntu 18 but im getting this issue

![image](https://user-images.githubusercontent.com/13953629/129659491-8c2e5ab5-5e24-4d45-9691-0cc38053e404.png)

`sudo pip install -U sqlalchemy==1.3.3 dpkt==1.8.7 jinja2==2.9.6 pymongo==3.0.3 bottle pefile yara-python==3.6.3 requests==2.13.0 python-dateutil==2.4.2 chardet==2.3.0 setuptools psycopg2 pycrypto pydeep distorm3 cuckoo weasyprint==0.36 m2crypto openpyxl ujson pycrypto pytz pyOpenSSL
`

**Comment by S4kur4** [comment]
It looks pefile installed failed, did u check any updates related to the Python version or some special changes for the library of pefile? Try to install pefile manually with a suitable version.

**Comment by killmasta93** [comment]
solved:

pip install --upgrade setuptools
pip install --upgrade pip

**Comment by killmasta93** [comment]
quick question so got it working but its stuck on pending task

**Comment by S4kur4** [comment]
> quick question so got it working but its stuck on pending task

Hey bro @killmasta93 ,  I have released a new script and there are multiple upgrades, invite you to take a test.
In addition, the root cause of "pending task" is a snapshot problem with the virtual machine, the script take a snapshot too early. You can change the waiting time longer (default 3m): 

https://github.com/S4kur4/AutoDeployCuckoo/blob/master/install.sh#L47

Or add your Ubuntu's CPU and memory, which can makes performance improve for virtualbox.
